/*
 * Copyright (c) 2017 Microchip Technology Inc. and its subsidiaries (Microchip). All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and limitations under the License.
 */

package com.microchip.mplab.nbide.embedded.arduino.wizard;

import javax.swing.JPanel;
import org.openide.util.NbBundle;

class ProjectSetupPanel extends JPanel {

    
    private final ProjectSetupStep control;  // R.I.P. Sir John Vincent Hurt (22 January 1940 – 25 January 2017)
    

    public ProjectSetupPanel(ProjectSetupStep control) {
        this.control = control;
        setName( NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.title") );
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialise the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel sourceProjectLocationLabel = new javax.swing.JLabel();
        sourceProjectLocationField = new javax.swing.JTextField();
        javax.swing.JButton sourceProjectLocationButton = new javax.swing.JButton();
        javax.swing.JLabel targetProjectLocationLabel = new javax.swing.JLabel();
        javax.swing.JButton targetProjectLocationButton = new javax.swing.JButton();
        targetProjectLocationField = new javax.swing.JTextField();
        javax.swing.JLabel platformLocationLabel = new javax.swing.JLabel();
        platformLocationField = new javax.swing.JTextField();
        javax.swing.JButton platformLocationButton = new javax.swing.JButton();
        javax.swing.JLabel boardLabel = new javax.swing.JLabel();
        boardCombo = new javax.swing.JComboBox<>();
        javax.swing.JLabel projectNameLabel = new javax.swing.JLabel();
        projectNameField = new javax.swing.JTextField();
        javax.swing.JLabel projectDirectoryLabel = new javax.swing.JLabel();
        projectDirectoryField = new javax.swing.JTextField();
        javax.swing.JLabel infoLabel = new javax.swing.JLabel();
        copyDependenciesCheckBox = new javax.swing.JCheckBox();
        overwriteCheckBox = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(sourceProjectLocationLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.sourceProjectLocationLabel.text")); // NOI18N

        sourceProjectLocationField.setText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.sourceProjectLocationField.text")); // NOI18N
        sourceProjectLocationField.setToolTipText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.sourceProjectLocationField.toolTipText")); // NOI18N
        sourceProjectLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceProjectLocationFieldActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(sourceProjectLocationButton, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.sourceProjectLocationButton.text")); // NOI18N
        sourceProjectLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceProjectLocationButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(targetProjectLocationLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.targetProjectLocationLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(targetProjectLocationButton, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.targetProjectLocationButton.text")); // NOI18N
        targetProjectLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetProjectLocationButtonActionPerformed(evt);
            }
        });

        targetProjectLocationField.setText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.targetProjectLocationField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(platformLocationLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.platformLocationLabel.text")); // NOI18N

        platformLocationField.setEditable(false);
        platformLocationField.setText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.platformLocationField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(platformLocationButton, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.platformLocationButton.text")); // NOI18N
        platformLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformLocationButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(boardLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.boardLabel.text")); // NOI18N

        boardCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boardComboItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(projectNameLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.projectNameLabel.text")); // NOI18N

        projectNameField.setText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.projectNameField.text")); // NOI18N
        projectNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectNameFieldKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(projectDirectoryLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.projectDirectoryLabel.text")); // NOI18N

        projectDirectoryField.setEditable(false);
        projectDirectoryField.setText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.projectDirectoryField.text")); // NOI18N
        projectDirectoryField.setToolTipText(org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.projectDirectoryField.toolTipText")); // NOI18N

        infoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/microchip/mplab/nbide/embedded/arduino/wizard/info_48.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(infoLabel, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.infoLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(copyDependenciesCheckBox, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.copyDependenciesCheckBox.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(overwriteCheckBox, org.openide.util.NbBundle.getMessage(ProjectSetupPanel.class, "ProjectSetupPanel.overwriteCheckBox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(projectDirectoryLabel)
                            .addComponent(projectNameLabel)
                            .addComponent(boardLabel)
                            .addComponent(platformLocationLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(targetProjectLocationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sourceProjectLocationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sourceProjectLocationField, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sourceProjectLocationButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(targetProjectLocationField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(targetProjectLocationButton))
                            .addComponent(boardCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(platformLocationField)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(platformLocationButton))
                            .addComponent(projectNameField)
                            .addComponent(projectDirectoryField)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(copyDependenciesCheckBox)
                                    .addComponent(overwriteCheckBox))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sourceProjectLocationLabel)
                    .addComponent(sourceProjectLocationButton)
                    .addComponent(sourceProjectLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetProjectLocationLabel)
                    .addComponent(targetProjectLocationButton)
                    .addComponent(targetProjectLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platformLocationLabel)
                    .addComponent(platformLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(platformLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boardLabel)
                    .addComponent(boardCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectDirectoryLabel)
                    .addComponent(projectDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(copyDependenciesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overwriteCheckBox)
                .addGap(0, 68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sourceProjectLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceProjectLocationFieldActionPerformed
        control.sourceProjectLocationButtonActionPerformed(evt);
    }//GEN-LAST:event_sourceProjectLocationFieldActionPerformed

    private void targetProjectLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetProjectLocationButtonActionPerformed
        control.targetProjectLocationButtonActionPerformed(evt);
    }//GEN-LAST:event_targetProjectLocationButtonActionPerformed

    private void sourceProjectLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceProjectLocationButtonActionPerformed
        control.sourceProjectLocationButtonActionPerformed(evt);
    }//GEN-LAST:event_sourceProjectLocationButtonActionPerformed

    private void platformLocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platformLocationButtonActionPerformed
        control.platformLocationButtonActionPerformed(evt);
    }//GEN-LAST:event_platformLocationButtonActionPerformed

    private void projectNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectNameFieldKeyReleased
        control.projectNameFieldKeyReleased(evt);
    }//GEN-LAST:event_projectNameFieldKeyReleased

    private void boardComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boardComboItemStateChanged
        control.boardComboItemStateChanged(evt);
    }//GEN-LAST:event_boardComboItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox<String> boardCombo;
    protected javax.swing.JCheckBox copyDependenciesCheckBox;
    protected javax.swing.JCheckBox overwriteCheckBox;
    protected javax.swing.JTextField platformLocationField;
    protected javax.swing.JTextField projectDirectoryField;
    protected javax.swing.JTextField projectNameField;
    protected javax.swing.JTextField sourceProjectLocationField;
    protected javax.swing.JTextField targetProjectLocationField;
    // End of variables declaration//GEN-END:variables

}
